### ISSUE TITLE
Not all bower_module fonts or css files make it to dist.dev.

### ISSUE THREAD

**Issue by chuckweinberger** [lordkada/healthy-gulp-angular#1]
For some reason, the glyphicon fonts that are part of Bootstrap are not making it to the dist.dev/fonts folder.  I've seen a similar problem where I've added some bower_modules that include required .css files, and not all of those .css files are making it to dist.dev/styles (e.g., malhar-angular-dashboard).

I can't figure out why; the file names do appear to pass your filtering functions.

![screen shot 2015-09-11 at 4 54 05 pm](https://cloud.githubusercontent.com/assets/410847/9828665/bdc8333e-58a5-11e5-80ca-cdad831a436d.png)

![screen shot 2015-09-11 at 4 52 54 pm](https://cloud.githubusercontent.com/assets/410847/9828652/94c82836-58a5-11e5-8d98-a05d53596de8.png)

**Comment by lordkada** [comment]
The list of files to be included comes from the **main** section within the **bower.json** file (in your case: **bower_components/bootstrap/bower.json**).

Unfortunately (and unlike font-awesome) fonts are not mentioned there:

>  "main": [
>    "less/bootstrap.less",
>    "dist/js/bootstrap.js"
>  ],

Hope it helps!

**Comment by chuckweinberger** [comment]
Thanks for pointing that out . . . I didn't realize that bowerFiles() relied upon the files listed as "main" in the bower.json files.  

I guess that it makes sense that the glyphicons aren't listed in "main" section of the Bootstrap bower.json file as many people use bootstrap without the glyphicons.
